_security_login:
    pattern: /login
    defaults: { _controller: UserBundle:User:login }

_security_check:
    pattern: /login_check

logout:
    pattern: /logout

UserIndex: 
    pattern: /index
    defaults: { _controller: UserBundle:User:login }    
    
register:    
    pattern: /register
    defaults: { _controller: UserBundle:User:addUser }
    
edituser:
    pattern: /edituser
    defaults: { _controller: UserBundle:User:editUser }
    
Creategroup:
    pattern: /creategroup
    defaults: { _controller: UserBundle:Group:createGroup }

Listgroup:    
    pattern: /listgroup
    defaults: { _controller: UserBundle:Group:listGroup }    
    
Editgroup:
    pattern: /editgroup
    defaults: { _controller: UserBundle:Group:editGroup }
    
Deletegroup:
    pattern: /deletegroup
    defaults: { _controller: UserBundle:Group:deleteGroup }

ListAllgroup:  
    pattern: /listallgroup
    defaults: { _controller: UserBundle:Group:listAllGroup }

Listsubscibedgroup:
    pattern: /Listsubscibedgroup
    defaults: { _controller: UserBundle:Group:listSubcribedGroup }

Subscribegroup:
    pattern: /subcribegroup
    defaults: { _controller: UserBundle:Group:subcribeGroup }

Unsubscribegroup:    
    pattern: /unsubcribegroup
    defaults: { _controller: UserBundle:Group:unsubcribeGroup }

