commentaire:
    pattern: /commentaire/view/{idu}
    defaults: { _controller: CommentaireBundle:Commentaire:getCommentaires }
add:
    pattern: /commentaire/add/{ida}
    defaults: { _controller: CommentaireBundle:Commentaire:index }
delete:
    pattern: /commentaire/delete/{id}/{idu}
    defaults: { _controller: CommentaireBundle:Commentaire:deleteCommentaire }

  