index:
    pattern:  /calendar
    defaults: { _controller: CalendarBundle:Calendar:index }

add:
    pattern: /calendar/add
    defaults: { _controller: CalendarBundle:Calendar:add }

delete:
    pattern: /calendar/delete/{id}
    defaults: { _controller: CalendarBundle:Calendar:delete }

update:
    pattern: /calendar/update/{id}
    defaults: { _controller: CalendarBundle:Calendar:update }
