event_index:
    pattern:  /calendar
    defaults: { _controller: CalendarBundle:Calendar:index }

event_add:
    pattern: /calendar/add
    defaults: { _controller: CalendarBundle:Calendar:add }

event_delete:
    pattern: /calendar/delete/{id}
    defaults: { _controller: CalendarBundle:Calendar:delete }

event_update:
    pattern: /calendar/update/{id}
    defaults: { _controller: CalendarBundle:Calendar:update }
